[files]
current_page=1
recent_files=/home/peter/.config/kanshi/config;/home/peter/.config/labwc/autostart;/home/peter/void-labwc/config/labwc/shutdown;/home/peter/void-labwc/config/labwc/menu.xml;/home/peter/void-labwc/config/labwc/themerc;
recent_projects=
FILE_NAME_0=755;None;0;EUTF-8;1;1;0;%2Fhome%2Fpeter%2F.config%2Flabwc%2Fautostart;0;4
FILE_NAME_1=53;Conf;0;EUTF-8;1;1;0;%2Fhome%2Fpeter%2F.config%2Fkanshi%2Fconfig;0;4

[VTE]
last_dir=/home/peter

[project]
session_file=
project_file_path=/home/peter/projects

[geany]
treeview_position=230
msgwindow_position=658
geometry=0;0;1512;890;0;
sidebar_page=0

[search]
find_all_expanded=false
replace_all_expanded=false
position_find_x=-1
position_find_y=-1
position_replace_x=-1
position_replace_y=-1
position_fif_x=-1
position_fif_y=-1

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;
